### PR TITLE
Maintenance/add example

### PR DESCRIPTION
**Pull request by Jeroen-Veltmans**
Adds an example project to easily test the project.

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
Were there any changes compared to [the example in react-native-theoplayer](https://github.com/THEOplayer/react-native-theoplayer/tree/e6448f845994bafd911916bff8440fed88a2f3f6/example)?

**Comment by Jeroen-Veltmans** [comment]
This example is only for android and ios for now, the UI itself in App.tsx is also a bit more basic but most of it is the same.

**Comment by MattiasBuelens** [comment]
It feels weird to have *two* examples for what is supposed to be a *cross-platform* UI. 😅

Are there any plans for merging the two examples into one that works on web, Android and iOS?

**Comment by MattiasBuelens** [comment]
Okay, I understand now. You want an example *inside your repo* so you can quickly test your changes while developing.

Then this is fine. 👍

**Review by tvanlaerhoven — APPROVED** [review]

**Pull request merged**
